### ISSUE TITLE
wordpress-alpine-php@0.8: bad watch-php-fpm.sh causes downtime

### ISSUE THREAD

**Issue by ericwong3** [Azure/app-service-quickstart-docker-images#337]
### This issue is for a: (mark with an `x`)

- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
> Generate high load on the server, may not always happens, I believe it is more easy to trigger when the machine first boots as opcache is not populated yet (see Observations section for reasoning).

### Observations (The section is added by me)
- After analyzing `watch-php-fpm.sh`, I learnt that the script is for killing php-fpm stuck in stat D, which is probably for killing php-fpm when it is stuck in IO. However, it uses `killall` on php-fpm, and it is important to note that supervisord is a process manager, it starts php-fpm; php-fpm itself is also a process manager, it starts php pool workers.
- In the logs, the two important time is **04-11 21:02** and **04-12 00:40**
- In the first time, from `supervisord.log`, php-fpm is killed by SIGKILL, probably by `watch-php-fpm.sh`, supervisord tried to respawn it 4 times but all failed with error 78, that corresponds to the 4 times the stderr log reading `Another FPM instance seems to already listen on /var/run/php/php-fpm.sock` (searching "php-fpm error 78" will see people explaining the same). However, there is only a small bump in Http 5xx metric, and the site remains running.
- This shows that although supervisord cannot restart php-fpm properly, in fact there is some php-fpm still running (and thus blocking new php-fpm from starting).
- On the second time, `supervisord.log` reports nginx is killed by SIGKILL (again presumably that by shell script), this time, nothing related to php-fpm has appeared on either log because supervisord has gave up on starting it.
- But knowing the shell script sends SIGKILL to nginx and php-fpm at the same time, this log reveals that at that point the "ghosted" php-fpm (not sure if it is practically a zombie process) received a SIGKILL, this time, without supervisord restarting php-fpm, the site is permanently entering 5xx.
- So with all the logs and above articulation, I suspect this is what happened:
1. At 04-11 21:02, `watch-php-fpm.sh` determined it is time to kill php-fpm and nginx as it saw stat D process for 15s.
2. In the first 0.12s of 21:02:21, each **child/PHP worker process** received SIGKILL, but php-fpm rapidly replaced them (thus the lines in stderr log)
3. On exactly 21:02:31,120, php master process received SIGKILL, thus the line in supervisord.log
4. For unknown reason, the master process' death does not kill the new children created in step 2
5. supervisord notice php master process' death and attempts to restart php-fpm
6. Restart of php-fpm failed continuously because the ghost php worker process is holding onto the socket, and the new php-fpm cannot access it. repeat 4 times until supervisord declares FATAL and give up monitoring
7. Site continues  to run normally by the ghost php workers
8. At **04-12 00:40**, the 15s of stat D happens again, nginx and php-fpm got killed, nginx is restarted by supervisord, but php-fpm is not.
9. Site is dead without php-fpm.

### Any log messages given by the failure
(Only relevant section is included)
App Service Http 5xx chart:
![image](https://user-images.githubusercontent.com/1881669/79065694-e08dd280-7ce4-11ea-9a9c-6207cb740293.png)

`/home/LogFiles/supervisor/supervisord.log`:
```
2020-04-11 13:10:00,063 INFO exited: php-fpm (terminated by SIGKILL; not expected)
2020-04-11 13:10:04,609 INFO spawned: 'php-fpm' with pid 71850
2020-04-11 13:10:04,610 INFO exited: nginx (terminated by SIGKILL; not expected)
2020-04-11 13:10:04,773 INFO spawned: 'nginx' with pid 71852
2020-04-11 13:10:05,902 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-11 13:10:05,903 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-11 21:02:31,120 INFO exited: php-fpm (terminated by SIGKILL; not expected)
2020-04-11 21:02:31,131 INFO spawned: 'php-fpm' with pid 61102
2020-04-11 21:02:31,231 INFO exited: nginx (terminated by SIGKILL; not expected)
2020-04-11 21:02:31,253 INFO spawned: 'nginx' with pid 61104
2020-04-11 21:02:31,490 INFO exited: php-fpm (exit status 78; not expected)
2020-04-11 21:02:32,493 INFO spawned: 'php-fpm' with pid 61105
2020-04-11 21:02:32,495 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-11 21:02:32,566 INFO exited: php-fpm (exit status 78; not expected)
2020-04-11 21:02:34,702 INFO spawned: 'php-fpm' with pid 61154
2020-04-11 21:02:34,965 INFO exited: php-fpm (exit status 78; not expected)
2020-04-11 21:02:37,972 INFO spawned: 'php-fpm' with pid 61168
2020-04-11 21:02:38,055 INFO exited: php-fpm (exit status 78; not expected)
2020-04-11 21:02:39,058 INFO gave up: php-fpm entered FATAL state, too many start retries too quickly
2020-04-12 00:40:57,178 INFO exited: nginx (terminated by SIGKILL; not expected)
2020-04-12 00:40:57,190 INFO spawned: 'nginx' with pid 116591
2020-04-12 00:40:58,234 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-12 08:42:54,067 INFO exited: nginx (terminated by SIGKILL; not expected)
2020-04-12 08:42:54,078 INFO spawned: 'nginx' with pid 108374
2020-04-12 08:42:55,239 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-12 08:44:33,657 INFO exited: nginx (terminated by SIGKILL; not expected)
2020-04-12 08:44:33,670 INFO spawned: 'nginx' with pid 108854
2020-04-12 08:44:34,713 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-12 09:08:35,604 INFO exited: nginx (terminated by SIGKILL; not expected)
2020-04-12 09:08:36,611 INFO spawned: 'nginx' with pid 115132
2020-04-12 09:08:37,659 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

`/tmp/php-fpm-stderr---supervisor-PYd1Kb.log`:
```
- -  11/Apr/2020:21:02:12 +0000 "GET /index.php" 200
- -  11/Apr/2020:21:02:12 +0000 "GET /index.php" 200
[11-Apr-2020 21:02:31] WARNING: [pool www] child 61001 exited on signal 9 (SIGKILL) after 20.905322 seconds from start
[11-Apr-2020 21:02:31] NOTICE: [pool www] child 61095 started
[11-Apr-2020 21:02:31] WARNING: [pool www] child 61007 exited on signal 9 (SIGKILL) after 19.935792 seconds from start
[11-Apr-2020 21:02:31] NOTICE: [pool www] child 61096 started
[11-Apr-2020 21:02:31] WARNING: [pool www] child 61011 exited on signal 9 (SIGKILL) after 19.940247 seconds from start
[11-Apr-2020 21:02:31] NOTICE: [pool www] child 61097 started
[11-Apr-2020 21:02:31] WARNING: [pool www] child 61019 exited on signal 9 (SIGKILL) after 18.942026 seconds from start
[11-Apr-2020 21:02:31] NOTICE: [pool www] child 61098 started
[11-Apr-2020 21:02:31] WARNING: [pool www] child 61020 exited on signal 9 (SIGKILL) after 18.943544 seconds from start
[11-Apr-2020 21:02:31] NOTICE: [pool www] child 61099 started
[11-Apr-2020 21:02:31] WARNING: [pool www] child 61021 exited on signal 9 (SIGKILL) after 18.944947 seconds from start
[11-Apr-2020 21:02:31] NOTICE: [pool www] child 61100 started
[11-Apr-2020 21:02:31] ERROR: Another FPM instance seems to already listen on /var/run/php/php-fpm.sock
[11-Apr-2020 21:02:31] ERROR: Another FPM instance seems to already listen on /var/run/php/php-fpm.sock
[11-Apr-2020 21:02:31] ERROR: FPM initialization failed
[11-Apr-2020 21:02:31] ERROR: FPM initialization failed
[11-Apr-2020 21:02:32] ERROR: Another FPM instance seems to already listen on /var/run/php/php-fpm.sock
[11-Apr-2020 21:02:32] ERROR: Another FPM instance seems to already listen on /var/run/php/php-fpm.sock
[11-Apr-2020 21:02:32] ERROR: FPM initialization failed
[11-Apr-2020 21:02:32] ERROR: FPM initialization failed
[11-Apr-2020 21:02:34] ERROR: Another FPM instance seems to already listen on /var/run/php/php-fpm.sock
[11-Apr-2020 21:02:34] ERROR: Another FPM instance seems to already listen on /var/run/php/php-fpm.sock
[11-Apr-2020 21:02:34] ERROR: FPM initialization failed
[11-Apr-2020 21:02:34] ERROR: FPM initialization failed
[11-Apr-2020 21:02:38] ERROR: Another FPM instance seems to already listen on /var/run/php/php-fpm.sock
[11-Apr-2020 21:02:38] ERROR: Another FPM instance seems to already listen on /var/run/php/php-fpm.sock
[11-Apr-2020 21:02:38] ERROR: FPM initialization failed
[11-Apr-2020 21:02:38] ERROR: FPM initialization failed
```

### Expected/desired behavior
(More of proposed solution)
Since php-fpm master process is itself a process manager, the script should not simultaneously kill PHP master and worker process. I believe the better way is to only kill worker, since as mentioned php-fpm is a process manager, so killing children will make master process restart them anyway.

Furthermore, the script is little bit overkill, there is no reason to kill all php-fpm if only one worker process is stuck in stat D, so it would be even better if the script can track worker process individually, and only kill those with stat D (as tested, master process seems will not enter stat D).

Also, Killing nginx seems be unnecessary (correct me if I am wrong)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by edisga** [comment]
Thank you for the detailed information and proposed solution. Can you please create a custom image based on this one and apply your suggestions and see how your site performs. Based on that we can try and merge those changes into this image. Also we are exploring other options to get a simple wordpress image, but there is no ETA.

**Comment by Klownicle** [comment]
Honorable mention, we deployed .8 of the docker image and have been experiencing with this since deployment as well.

**Comment by Klownicle** [comment]
> Honorable mention, we deployed .8 of the docker image and have been experiencing with this since deployment as well.

Can confirm, site has been stable since applying the fix.  Unfortunately, I am not versed with Docker enough about creating custom images.  So i'm resorting to manually modify.  Once we restart the Azure App Service, the site becomes unstable again till the fix is applied.

**Comment by ericwong3** [comment]
@Klownicle I saw you have seen my pull request, actually you can go over to [my branch](https://github.com/ericwong3/app-service-quickstart-docker-images/tree/build-test/wordpress-alpine-php/0.81),which contains the patched script along with Dockerfile.

You can simply pull the repo, cd into wordpress-alpine-php/0.81/``, and follow the [Docker Hub Quickstart](https://docs.docker.com/docker-hub/) to build and deploy to a free DockerHub account.

Good luck.

**Comment by Klownicle** [comment]
> @Klownicle I saw you have seen my pull request, actually you can go over to [my branch](https://github.com/ericwong3/app-service-quickstart-docker-images/tree/build-test/wordpress-alpine-php/0.81), which contains the patched script along with Dockerfile.
> 
> You can simply pull the repo, cd into `wordpress-alpine-php/0.81/`, and follow the [Docker Hub Quickstart](https://docs.docker.com/docker-hub/) to build and deploy to a free DockerHub account.
> 
> Good luck.

Well, I THINK I did it.  Ran into a number of little quirks doing it locally on my PC but ended up succeeding, tho haven't deployed to azure yet.  Need a change for "let's see what happens..." Lol.  It runs locally on my computer, was able to get the MariaDB working and setup a blank wordpress.  Tho when I shut down the container to see if things stuck as configured (with the storage env as true), nginx closes on startup after it all starts.  So not sure about that.  But logistically, without the Maria DB (which we don't use on the site), it was restarting fine each time.  I'm sure it's something I'm doing.  That was a fun couple of hours with my wham bam thank you mam intro into docker and git. 

Thanks!

**Comment by jbermudezcabrera** [comment]
Any ETA on this? I'm using 0.9 and I can confirm the issue is still active. 
@Klownicle do you know how I can(if possible) apply your fix on a running site at least until it gets restarted?

**Comment by Klownicle** [comment]
> Any ETA on this? I'm using 0.9 and I can confirm the issue is still active.
> @Klownicle do you know how I can(if possible) apply your fix on a running site at least until it gets restarted?

I can confirm the applied fix on a custom docker image works and has been stable since.  I sent you an email.
